name: push
"on":
  push:
    branches:
      - master
jobs:
  publish:
    environment:
      name: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish the package
        uses: dycw/action-publish-package@latest
        with: {}
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Tag the latest commit
        uses: dycw/action-tag-commit@latest
        with: {}
  publish-package:
    environment:
      name: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish the package
        uses: dycw/action-publish-package@latest
        with: {}
